"""
Complete workflow example combining all three traffic sign recognition approaches.

This script demonstrates how to use Florence, OpenCLIP, and Mapillary together
for comprehensive traffic sign recognition and analysis.
"""

import sys
import os

# Add parent directory to path to import traffic_sign module
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))


def workflow_example():
    """Demonstrate complete traffic sign recognition workflow."""
    
    print("=" * 70)
    print("Complete Traffic Sign Recognition Workflow")
    print("=" * 70)
    print()
    
    print("This workflow demonstrates how to combine all three approaches:")
    print("  1. Florence - Generate descriptions of traffic signs")
    print("  2. OpenCLIP - Match images with description database")
    print("  3. Mapillary - Detect traffic signs in geographic areas")
    print()
    
    print("=" * 70)
    print("STEP 1: Use Mapillary to find traffic signs in an area")
    print("=" * 70)
    print()
    print("from traffic_sign.mapillary import MapillarySignDetector")
    print()
    print("# Initialize detector")
    print("detector = MapillarySignDetector(access_token='your_token')")
    print()
    print("# Search for signs in Paris center")
    print("bbox = (2.3, 48.85, 2.35, 48.87)  # (min_lon, min_lat, max_lon, max_lat)")
    print("signs = detector.search_traffic_signs(bbox, limit=50)")
    print()
    print("# Get images with traffic signs")
    print("images = detector.search_images_with_signs(bbox, limit=20)")
    print("print(f'Found {len(images)} images with traffic signs')")
    print()
    
    print("=" * 70)
    print("STEP 2: Use Florence to describe the detected signs")
    print("=" * 70)
    print()
    print("from traffic_sign.florence import FlorenceDescriptor")
    print()
    print("# Initialize Florence descriptor")
    print("descriptor = FlorenceDescriptor()")
    print()
    print("# Describe each sign image")
    print("descriptions = []")
    print("for img in images[:5]:  # Process first 5 images")
    print("    # Download image (simplified)")
    print("    image_url = img.get('thumb_2048_url')")
    print("    # ... download image ...")
    print("    ")
    print("    # Generate description")
    print("    desc = descriptor.describe_traffic_sign('downloaded_image.jpg')")
    print("    descriptions.append(desc)")
    print("    print(f'Image {img[\"id\"]}: {desc}')")
    print()
    
    print("=" * 70)
    print("STEP 3: Use OpenCLIP to match signs with database")
    print("=" * 70)
    print()
    print("from traffic_sign.openclip import TrafficSignMatcher")
    print()
    print("# Initialize matcher")
    print("matcher = TrafficSignMatcher()")
    print()
    print("# Load descriptions database (could use Florence descriptions)")
    print("description_database = [")
    print("    'stop sign, red octagonal sign with white text',")
    print("    'yield sign, red and white downward pointing triangle',")
    print("    'speed limit sign showing 50 km/h',")
    print("    # ... more descriptions ...")
    print("]")
    print("matcher.load_descriptions_database(description_database)")
    print()
    print("# Match each image with the database")
    print("for img_path in ['sign1.jpg', 'sign2.jpg', 'sign3.jpg']:")
    print("    matches = matcher.find_best_match(img_path, top_k=3)")
    print("    print(f'\\nMatches for {img_path}:')")
    print("    for desc, score in matches:")
    print("        print(f'  {desc}: {score:.3f}')")
    print()
    
    print("=" * 70)
    print("STEP 4: Complete analysis pipeline")
    print("=" * 70)
    print()
    print("# Combine all three for comprehensive analysis")
    print("def analyze_traffic_sign(image_path):")
    print("    # 1. Generate AI description")
    print("    florence_desc = descriptor.describe_traffic_sign(image_path)")
    print("    ")
    print("    # 2. Match with known signs")
    print("    matches = matcher.find_best_match(image_path, top_k=1)")
    print("    best_match, confidence = matches[0]")
    print("    ")
    print("    # 3. Return comprehensive analysis")
    print("    return {")
    print("        'ai_description': florence_desc,")
    print("        'matched_type': best_match,")
    print("        'confidence': confidence")
    print("    }")
    print()
    print("# Process multiple signs")
    print("for sign_path in detected_sign_images:")
    print("    result = analyze_traffic_sign(sign_path)")
    print("    print(f'Sign: {sign_path}')")
    print("    print(f'  Description: {result[\"ai_description\"]}')")
    print("    print(f'  Type: {result[\"matched_type\"]}')")
    print("    print(f'  Confidence: {result[\"confidence\"]:.3f}')")
    print()
    
    print("=" * 70)
    print("Expected Output Example")
    print("=" * 70)
    print()
    print("Sign: paris_sign_001.jpg")
    print("  Description: A red octagonal stop sign with white border and STOP text")
    print("  Type: stop sign, red octagonal sign with white text")
    print("  Confidence: 0.945")
    print()
    print("Sign: paris_sign_002.jpg")
    print("  Description: A circular blue sign showing a pedestrian crossing symbol")
    print("  Type: pedestrian crossing sign, blue with white figures")
    print("  Confidence: 0.887")
    print()
    
    print("=" * 70)
    print("Use Cases for Combined Workflow")
    print("=" * 70)
    print()
    print("1. Traffic Sign Inventory:")
    print("   - Use Mapillary to find all signs in a city")
    print("   - Use Florence to generate descriptions")
    print("   - Build a comprehensive database")
    print()
    print("2. Sign Recognition System:")
    print("   - Use Florence for new unknown signs")
    print("   - Use OpenCLIP to match with known signs")
    print("   - Validate with Mapillary data")
    print()
    print("3. Quality Assurance:")
    print("   - Compare Mapillary detections with AI descriptions")
    print("   - Verify sign database accuracy")
    print("   - Identify misclassified signs")
    print()
    print("4. Research and Analysis:")
    print("   - Study sign distribution patterns")
    print("   - Analyze sign variations across regions")
    print("   - Build training datasets")
    print()


def main():
    """Run the workflow example."""
    workflow_example()


if __name__ == "__main__":
    main()
